spring:
  application:
    name: thesis
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
  datasource:
    password: ${POSTGRES_PASSWORD}
    username: ${POSTGRES_USER}
    url: jdbc:postgresql://localhost:5432/thesis-postgres
#    url: jdbc:postgresql://thesis-postgres:5432/thesis-postgres

upload:
  directory: ./uploads

logging:
  level:
    root: error

server:
  port: 8080

security:
  configuration:
    admin: 182077829, 180645494, 181595941