spring.application.name=thesis
logging.level.root=error

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.security.oauth2.client.registration.github.client-id: ${CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret: ${CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope: read:public_repo